// @examples/react-with-alien-signals/src/App.tsx
import './App.css';

import { useSignal } from '@gn8/alien-signals-react';
import { signal } from 'alien-signals';

/**
 * Count signal.
 */
const countSignal = signal(0);

/**
 * Top page component.
 *
 * @jsx
 */
export default function App() {
  const [count, setCount] = useSignal(countSignal);

  return (
    <>
      <div>
        <a href="https://react.dev" target="_blank">
          <img className="logo react" alt="React logo" src="/react.svg" />
        </a>
      </div>
      <h1>React</h1>
      <div className="card">
        <button onClick={() => setCount(count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the React logo to learn more</p>
    </>
  );
}

// @examples/vue-with-alien-signals/src/App.vue
<script setup lang="ts">
import { useSignal } from '@gn8/alien-signals-vue';
import { signal } from 'alien-signals';

/**
 * Count signal.
 */
const countSignal = signal(0);

/**
 * Count vue signal.
 */
const count = useSignal(countSignal);
</script>

<template>
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img class="logo vue" alt="Vue logo" src="/vue.svg" />
    </a>
  </div>
  <h1>Vue</h1>
  <div class="card">
    <button @click="count++">count is {{ count }}</button>
    <p>
      Edit
      <code>src/App.vue</code>
      and save to test HMR
    </p>
  </div>
  <p class="read-the-docs">Click on the Vue logo to learn more</p>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
